package cz.kaboom.connectioninfo.feature.main

/** Shared English UI copy used by Android and iOS to keep both apps visually identical. */
internal object UiText {
    const val speedTest = "Speed Test"
    const val networkInfo = "Network Info"
    const val version = "Version %s"
    const val copyright = "Copyright © KaBoom Software"
    const val speed = "Speed"
    const val stopTest = "Stop Test"
    const val startTest = "Start Test"
    const val networkUnavailable = "Network unavailable"
    const val loading = "Loading..."
    const val notAvailable = "--"
    const val status = "Status"
    const val last = "Last"
    const val max = "Max"
    const val avg = "Avg"
    const val avgShort = "Avg:"
    const val best = "Best:"
    const val download = "Download"
    const val upload = "Upload"
    const val ping = "Ping"
    const val latency = "Latency"
    const val network = "Network"
    const val internalIp = "Internal IP"
    const val externalIp = "External IP"
    const val isp = "ISP"
    const val org = "Org"
    const val city = "City"
    const val region = "Region"
    const val regionName = "Region Name"
    const val country = "Country"
    const val countryCode = "Country Code"
    const val latitude = "Latitude"
    const val longitude = "Longitude"
}
