package cz.kaboom.connectioninfo.feature.main

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Responsive sizing values for compact phones, regular phones, and expanded devices. */
internal data class MainLayoutSpec(
    val contentMaxWidth: Dp,
    val horizontalPadding: Dp,
    val speedVerticalPadding: Dp,
    val networkVerticalPadding: Dp,
    val tabHeight: Dp,
    val tabItemHeight: Dp,
    val tabFontSize: TextUnit,
    val tabLetterSpacing: TextUnit,
    val tabIndicatorWidth: Dp,
    val tabIndicatorTopSpacing: Dp,
    val footerVerticalPadding: Dp,
    val versionTextSize: TextUnit,
    val copyrightTextSize: TextUnit,
    val gaugeHeight: Dp,
    val gaugeFillFraction: Float,
    val gaugeStrokeWidth: Dp,
    val gaugeValueLargeTextSize: TextUnit,
    val gaugeValueSmallTextSize: TextUnit,
    val gaugeUnitTextSize: TextUnit,
    val sectionTitleTextSize: TextUnit,
    val statsHorizontalPadding: Dp,
    val statsVerticalPadding: Dp,
    val statsDividerVerticalPadding: Dp,
    val statsLabelWidth: Dp,
    val statsRowHeight: Dp,
    val pingRowHeight: Dp,
    val pingLabelTextSize: TextUnit,
    val pingSubtitleTextSize: TextUnit,
    val pingCurrentTextSize: TextUnit,
    val pingMetaTextSize: TextUnit,
    val pingMetaLineHeight: TextUnit,
    val statsHeaderTextSize: TextUnit,
    val statsLabelTextSize: TextUnit,
    val statsValueTextSize: TextUnit,
    val statsValueCompactTextSize: TextUnit,
    val buttonHeight: Dp,
    val actionTopPadding: Dp,
    val actionTextSize: TextUnit,
    val progressTopPadding: Dp,
    val networkLabelWidth: Dp,
    val networkCardHorizontalPadding: Dp,
    val networkCardVerticalPadding: Dp,
    val networkRowVerticalPadding: Dp,
    val networkTextSize: TextUnit,
    val networkValueLineHeight: TextUnit
)

/** Default (normal phone) layout used as the baseline for all breakpoints. */
private val NormalSpec = MainLayoutSpec(
    contentMaxWidth = 520.dp,
    horizontalPadding = 20.dp,
    speedVerticalPadding = 12.dp,
    networkVerticalPadding = 22.dp,
    tabHeight = 76.dp,
    tabItemHeight = 64.dp,
    tabFontSize = 15.sp,
    tabLetterSpacing = 0.sp,
    tabIndicatorWidth = 108.dp,
    tabIndicatorTopSpacing = 14.dp,
    footerVerticalPadding = 10.dp,
    versionTextSize = 13.sp,
    copyrightTextSize = 11.sp,
    gaugeHeight = 230.dp,
    gaugeFillFraction = 0.64f,
    gaugeStrokeWidth = 32.dp,
    gaugeValueLargeTextSize = 46.sp,
    gaugeValueSmallTextSize = 40.sp,
    gaugeUnitTextSize = 15.sp,
    sectionTitleTextSize = 18.sp,
    statsHorizontalPadding = 16.dp,
    statsVerticalPadding = 12.dp,
    statsDividerVerticalPadding = 8.dp,
    statsLabelWidth = 88.dp,
    statsRowHeight = 38.dp,
    pingRowHeight = 44.dp,
    pingLabelTextSize = 15.sp,
    pingSubtitleTextSize = 11.sp,
    pingCurrentTextSize = 19.sp,
    pingMetaTextSize = 10.sp,
    pingMetaLineHeight = 12.sp,
    statsHeaderTextSize = 12.sp,
    statsLabelTextSize = 15.sp,
    statsValueTextSize = 11.sp,
    statsValueCompactTextSize = 9.sp,
    buttonHeight = 58.dp,
    actionTopPadding = 18.dp,
    actionTextSize = 14.sp,
    progressTopPadding = 12.dp,
    networkLabelWidth = 120.dp,
    networkCardHorizontalPadding = 14.dp,
    networkCardVerticalPadding = 13.dp,
    networkRowVerticalPadding = 5.dp,
    networkTextSize = 13.sp,
    networkValueLineHeight = 18.sp
)

/** Picks the layout density from the actual available window size. */
internal fun mainLayoutSpec(maxWidth: Dp, maxHeight: Dp): MainLayoutSpec {
    val tinyPhone = maxWidth <= 375.dp || maxHeight <= 700.dp
    val compact = maxWidth < 390.dp || maxHeight < 780.dp
    val expanded = maxWidth >= 700.dp || maxHeight >= 900.dp

    return when {
        tinyPhone -> NormalSpec.copy(
            contentMaxWidth = 390.dp,
            horizontalPadding = 12.dp,
            speedVerticalPadding = 28.dp,
            networkVerticalPadding = 8.dp,
            tabHeight = 54.dp,
            tabItemHeight = 48.dp,
            tabFontSize = 12.sp,
            tabIndicatorWidth = 82.dp,
            tabIndicatorTopSpacing = 7.dp,
            footerVerticalPadding = 4.dp,
            versionTextSize = 11.sp,
            copyrightTextSize = 9.sp,
            gaugeHeight = 156.dp,
            gaugeFillFraction = 0.58f,
            gaugeStrokeWidth = 20.dp,
            gaugeValueLargeTextSize = 34.sp,
            gaugeValueSmallTextSize = 30.sp,
            gaugeUnitTextSize = 12.sp,
            sectionTitleTextSize = 15.sp,
            statsHorizontalPadding = 10.dp,
            statsVerticalPadding = 8.dp,
            statsDividerVerticalPadding = 4.dp,
            statsLabelWidth = 72.dp,
            statsRowHeight = 30.dp,
            pingLabelTextSize = 13.sp,
            pingSubtitleTextSize = 9.sp,
            pingCurrentTextSize = 16.sp,
            pingMetaTextSize = 8.sp,
            pingMetaLineHeight = 10.sp,
            statsHeaderTextSize = 10.sp,
            statsLabelTextSize = 12.sp,
            statsValueTextSize = 9.sp,
            statsValueCompactTextSize = 7.sp,
            buttonHeight = 46.dp,
            actionTopPadding = 10.dp,
            actionTextSize = 12.sp,
            progressTopPadding = 8.dp,
            networkLabelWidth = 96.dp,
            networkCardHorizontalPadding = 10.dp,
            networkCardVerticalPadding = 10.dp,
            networkRowVerticalPadding = 3.dp,
            networkTextSize = 11.sp,
            networkValueLineHeight = 14.sp
        )

        compact -> NormalSpec.copy(
            contentMaxWidth = 430.dp,
            horizontalPadding = 14.dp,
            speedVerticalPadding = 24.dp,
            networkVerticalPadding = 12.dp,
            tabHeight = 60.dp,
            tabItemHeight = 52.dp,
            tabFontSize = 13.sp,
            tabIndicatorWidth = 88.dp,
            tabIndicatorTopSpacing = 8.dp,
            footerVerticalPadding = 6.dp,
            versionTextSize = 12.sp,
            copyrightTextSize = 10.sp,
            gaugeHeight = 176.dp,
            gaugeFillFraction = 0.60f,
            gaugeStrokeWidth = 24.dp,
            gaugeValueLargeTextSize = 38.sp,
            gaugeValueSmallTextSize = 34.sp,
            gaugeUnitTextSize = 13.sp,
            sectionTitleTextSize = 16.sp,
            statsHorizontalPadding = 12.dp,
            statsVerticalPadding = 9.dp,
            statsDividerVerticalPadding = 5.dp,
            statsLabelWidth = 78.dp,
            statsRowHeight = 32.dp,
            pingLabelTextSize = 15.sp,
            pingSubtitleTextSize = 10.sp,
            pingCurrentTextSize = 18.sp,
            pingMetaTextSize = 9.sp,
            pingMetaLineHeight = 11.sp,
            statsHeaderTextSize = 11.sp,
            statsLabelTextSize = 14.sp,
            statsValueTextSize = 10.sp,
            statsValueCompactTextSize = 8.sp,
            buttonHeight = 52.dp,
            actionTopPadding = 14.dp,
            actionTextSize = 13.sp,
            progressTopPadding = 10.dp,
            networkLabelWidth = 108.dp,
            networkCardHorizontalPadding = 12.dp,
            networkCardVerticalPadding = 12.dp,
            networkRowVerticalPadding = 4.dp,
            networkTextSize = 12.sp,
            networkValueLineHeight = 16.sp
        )

        expanded -> NormalSpec.copy(
            contentMaxWidth = 760.dp,
            horizontalPadding = 44.dp,
            speedVerticalPadding = 34.dp,
            networkVerticalPadding = 44.dp,
            tabHeight = 104.dp,
            tabItemHeight = 84.dp,
            tabFontSize = 18.sp,
            tabIndicatorWidth = 138.dp,
            tabIndicatorTopSpacing = 20.dp,
            footerVerticalPadding = 16.dp,
            versionTextSize = 15.sp,
            copyrightTextSize = 13.sp,
            gaugeHeight = 360.dp,
            gaugeFillFraction = 0.68f,
            gaugeStrokeWidth = 42.dp,
            gaugeValueLargeTextSize = 60.sp,
            gaugeValueSmallTextSize = 52.sp,
            gaugeUnitTextSize = 18.sp,
            sectionTitleTextSize = 23.sp,
            statsHorizontalPadding = 24.dp,
            statsVerticalPadding = 18.dp,
            statsDividerVerticalPadding = 12.dp,
            statsLabelWidth = 118.dp,
            statsRowHeight = 48.dp,
            pingRowHeight = 56.dp,
            pingLabelTextSize = 19.sp,
            pingSubtitleTextSize = 13.sp,
            pingCurrentTextSize = 24.sp,
            pingMetaTextSize = 12.sp,
            pingMetaLineHeight = 15.sp,
            statsHeaderTextSize = 14.sp,
            statsLabelTextSize = 18.sp,
            statsValueTextSize = 13.sp,
            statsValueCompactTextSize = 11.sp,
            buttonHeight = 72.dp,
            actionTopPadding = 28.dp,
            actionTextSize = 16.sp,
            progressTopPadding = 18.dp,
            networkLabelWidth = 160.dp,
            networkCardHorizontalPadding = 24.dp,
            networkCardVerticalPadding = 22.dp,
            networkRowVerticalPadding = 8.dp,
            networkTextSize = 15.sp,
            networkValueLineHeight = 21.sp
        )

        else -> NormalSpec
    }
}
